"""Static HTML fallback for the Gradio demo - same precomputed content
(same manifest.json, same images), no Python/Gradio server needed to view
it. Every image is embedded as a base64 data URI so the single output file
is self-contained and works offline, double-clickable in any browser.

    python -m src.demo.precompute      # once, if demo_data/manifest.json is missing
    python -m src.demo.static_demo     # writes demo.html
"""
from __future__ import annotations

import base64
import json
from pathlib import Path

from src.demo.app import load_manifest
from src.demo.precompute import PANEL_ORDER, _demo_data_dir

OUT_PATH = Path(__file__).resolve().parents[2] / "demo.html"


def _b64_image(path: Path) -> str:
    return "data:image/png;base64," + base64.b64encode(path.read_bytes()).decode("ascii")


def build_html(manifest: dict, data_dir: Path) -> str:
    combos_js = []
    for combo in manifest["combos"]:
        panels_js = {}
        for key in PANEL_ORDER:
            panel = combo["panels"].get(key, {"error": "not computed"})
            if "error" in panel:
                panels_js[key] = dict(error=panel["error"])
            else:
                panels_js[key] = dict(
                    image=_b64_image(data_dir / panel["image"]),
                    heatmap=_b64_image(data_dir / panel["heatmap"]),
                    score=round(panel["score"], 4),
                    mean_anomaly=round(panel["mean_anomaly"], 4),
                    relative_drr=round(panel["relative_drr"], 3),
                    residual_corr=round(panel["residual_corr"], 3),
                )
        combos_js.append(dict(
            id=combo["id"], category=combo["category"], kind=combo["kind"],
            family=combo["family"], severity=combo["severity"], panels=panels_js,
        ))

    data_json = json.dumps(dict(
        combos=combos_js, panel_order=PANEL_ORDER, panel_labels=manifest["panel_labels"],
        striking_case_id=manifest.get("striking_case_id"),
        striking_case_note=manifest.get("striking_case_note", ""),
    ))
    detector_note = manifest["detector_choice_note"]
    score_note = manifest["score_note"]

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>DIVIDE demo (static)</title>
<style>
  body {{ font-family: system-ui, sans-serif; margin: 2rem; background: #fafafa; color: #111; }}
  h1 {{ font-size: 1.4rem; }}
  .note {{ background: #fff3cd; border: 1px solid #e0c26a; border-radius: 6px; padding: 0.8rem 1rem; margin: 1rem 0; font-size: 0.92rem; }}
  select {{ font-size: 1rem; padding: 0.3rem; margin-bottom: 1rem; }}
  .scene {{ font-weight: 600; margin-bottom: 1rem; }}
  .panels {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 1rem; }}
  .panel {{ background: white; border: 1px solid #ddd; border-radius: 8px; padding: 0.6rem; }}
  .panel h3 {{ font-size: 0.95rem; margin: 0 0 0.5rem 0; }}
  .panel img {{ width: 100%; border-radius: 4px; display: block; margin-bottom: 0.4rem; }}
  .panel .imgs {{ display: flex; gap: 0.4rem; }}
  .panel .imgs > div {{ flex: 1; }}
  .panel .imgs label {{ font-size: 0.72rem; color: #666; }}
  .panel pre {{ font-size: 0.8rem; background: #f4f4f4; padding: 0.4rem; border-radius: 4px; white-space: pre-wrap; margin: 0; }}
  .unavailable {{ color: #a33; font-size: 0.85rem; }}
  footer {{ margin-top: 2rem; font-size: 0.8rem; color: #888; }}
</style>
</head>
<body>
<h1>DIVIDE - does inverse-degradation restoration help detection?</h1>
<p>Static fallback: same precomputed data as the Gradio demo, no server needed. Every number here was computed once by <code>src.demo.precompute</code>, not live.</p>
<div class="note"><strong>Detector: PatchCore.</strong> {detector_note}</div>
<div class="note"><strong>On the "score" number:</strong> {score_note}</div>
<label for="combo-select">Precomputed example:</label><br>
<select id="combo-select"></select>
<div class="scene" id="scene-label"></div>
<div class="panels" id="panels"></div>
<footer>Generated by src/demo/static_demo.py from demo_data/manifest.json.</footer>
<script>
const DATA = {data_json};

function renderPanel(container, key, panel) {{
  const label = DATA.panel_labels[key];
  let html = `<h3>${{label}}</h3>`;
  if (panel.error) {{
    html += `<div class="unavailable">UNAVAILABLE:<br>${{panel.error}}</div>`;
  }} else {{
    html += `<div class="imgs">
      <div><label>restored image</label><img src="${{panel.image}}"></div>
      <div><label>PatchCore heatmap</label><img src="${{panel.heatmap}}"></div>
    </div>
    <pre>score = ${{panel.score}}  (mean anomaly = ${{panel.mean_anomaly}})
relative DRR = ${{panel.relative_drr}}
residual corr = ${{panel.residual_corr}}</pre>`;
  }}
  container.innerHTML = html;
}}

function render(comboId) {{
  const combo = DATA.combos.find(c => c.id === comboId);
  let label = `${{combo.category}} / ${{combo.kind}} defect / ${{combo.family}} severity ${{combo.severity}}`;
  if (comboId === DATA.striking_case_id) {{
    label += `<br><strong>This is the project's clearest side-by-side.</strong> ${{DATA.striking_case_note}}`;
  }}
  document.getElementById('scene-label').innerHTML = label;
  const panelsDiv = document.getElementById('panels');
  panelsDiv.innerHTML = '';
  for (const key of DATA.panel_order) {{
    const div = document.createElement('div');
    div.className = 'panel';
    renderPanel(div, key, combo.panels[key] || {{error: 'not computed'}});
    panelsDiv.appendChild(div);
  }}
}}

const select = document.getElementById('combo-select');
for (const combo of DATA.combos) {{
  const opt = document.createElement('option');
  opt.value = combo.id;
  opt.textContent = combo.id;
  select.appendChild(opt);
}}
select.value = DATA.striking_case_id || DATA.combos[0].id;
select.addEventListener('change', () => render(select.value));
render(select.value);
</script>
</body>
</html>
"""


def main() -> int:
    manifest = load_manifest()
    data_dir = _demo_data_dir()
    html = build_html(manifest, data_dir)
    OUT_PATH.write_text(html, encoding="utf-8")
    size_mb = len(html.encode("utf-8")) / 1e6
    print(f"wrote {OUT_PATH} ({size_mb:.1f} MB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
